
[client]
showSidebarNavigation = false
toolbarMode = "viewer"


[theme]
primaryColor="#006A71"
backgroundColor="#F2EFE7"
secondaryBackgroundColor="#48A6A7"
textColor="#1B1B1B"
font="sans serif"

[ui]
hideTopBar = true